### ISSUE TITLE
parsing fails for ranges

### ISSUE THREAD

**Issue by azaroth42** [iiif-prezi/iiif-prezi#19]
When parsing the attached manifest, master results in the following error:

```
[rsanderson@GT26940 iiif-prezi (master)]$ python -i ./test.py 
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    mr.read()
  File "/Users/rsanderson/Development/IIIF/code/iiif-prezi/iiif_prezi/loader.py", line 146, in read
    top = self.readObject(js)
  File "/Users/rsanderson/Development/IIIF/code/iiif-prezi/iiif_prezi/loader.py", line 285, in readObject
    subo = self.readObject(sub, what, k)
  File "/Users/rsanderson/Development/IIIF/code/iiif-prezi/iiif_prezi/loader.py", line 293, in readObject
    addfn(sub)
  File "/Users/rsanderson/Development/IIIF/code/iiif-prezi/iiif_prezi/factory.py", line 1418, in add_range
    self.ranges.append(rng.id)		
AttributeError: 'unicode' object has no attribute 'id'
```

Which is clearly a bug!

[manifest.json.zip](https://github.com/iiif-prezi/iiif-prezi/files/650287/manifest.json.zip)

**Comment by azaroth42** [comment]
Fixed!
