### ISSUE TITLE
UnboundLocalError: local variable 'lh' referenced before assignment

### ISSUE THREAD

**Issue by adrianh-cogapp** [iiif-prezi/iiif-prezi#27]
When trying to validate one of our manifests I am getting this error:
```
UnboundLocalError: local variable 'lh' referenced before assignment
```

Stacktrace:

```
Traceback (most recent call last):
 File "/Library/Python/2.7/site-packages/bottle-0.12.13-py2.7.egg/bottle.py", line 862, in _handle
   return route.call(**args)
 File "/Library/Python/2.7/site-packages/bottle-0.12.13-py2.7.egg/bottle.py", line 1740, in wrapper
   rv = callback(*a, **ka)
 File "iiif-presentation-validator.py", line 110, in do_GET_test
   return self.check_manifest(data, version, warnings)
 File "iiif-presentation-validator.py", line 55, in check_manifest
   mf = reader.read()
 File "/Library/Python/2.7/site-packages/iiif_prezi-0.2.5-py2.7.egg/iiif_prezi/loader.py", line 148, in read
   top = self.readObject(js)
 File "/Library/Python/2.7/site-packages/iiif_prezi-0.2.5-py2.7.egg/iiif_prezi/loader.py", line 341, in readObject
   what.set_metadata(lh)
UnboundLocalError: local variable 'lh' referenced before assignment
```

One of the manifests that is causing this error:

http://www.qdl.qa/en/iiif/81055/vdc_100000000282.0x0001ad/manifest

Please let me know if you need more details.

**Comment by zimeon** [comment]
Thanks @adrianh-cogapp , that is enough detail, there is an obvious error around line 334 in iiif_prezi/loader.py, in a case not covered by the tests :-(

**Comment by zimeon** [comment]
Have pushed to pypi as 0.2.6

**Comment by zimeon** [comment]
Let's make that 0.2.7 on pypi... as I messed up 0.2.6
