### ISSUE TITLE
iiif_prezi.factory.RequirementError: Resource type 'sc:Manifest' requires 'label' to be set

### ISSUE THREAD

**Issue by lguariento** [iiif-prezi/iiif-prezi#59]
Hello,

I have the simple (I think) need to generate a manifest file from a directory full of .jp2 files. The directory is already served from a IIIF server and accessible.

When running `python build-from-directory.py` I get this error:

```
python build-from-directory.py 
Traceback (most recent call last):
  File "/Users/luca/Documents/development/iiif-prezi/examples/build-from-directory.py", line 29, in <module>
    mfst.toFile(compact=False)
  File "/Users/luca/Documents/development/my_venv_3/lib/python3.9/site-packages/iiif_prezi/factory.py", line 793, in toFile
    js = self.toJSON(top=True)
  File "/Users/luca/Documents/development/my_venv_3/lib/python3.9/site-packages/iiif_prezi/factory.py", line 679, in toJSON
    raise RequirementError(
iiif_prezi.factory.RequirementError: Resource type 'sc:Manifest' requires 'label' to be set
```

Also, what should I put in / is the `set_base_prezi_uri`?
Can you please help me troubleshooting what's wrong?

Thank you.

**Comment by lguariento** [comment]
Apologies, that was a stupid question, I found out the culprit, i.e. the code for generating the label, which had to be customised according to my needs.
