### ISSUE TITLE
Build prezi 3 from JSON Schema

### ISSUE THREAD

**Issue by glenrobson** [iiif-prezi/iiif-prezi#63]
Is there a way to build a prezi3 library from the JSON schema using a ORM type program. One possibility is:

https://statham-schema.readthedocs.io/en/latest/quickstart.html#generating-models

This could build a python file containing all of the classes required. Updates to the schema and generated file could be difficult but this is also covered in:

https://statham-schema.readthedocs.io/en/latest/advanced.html#updating-generated-models-against-schema-changes

**Comment by mbennett-uoe** [comment]
A brief scan over the Statham docs suggest that converting the JSON-LD schema first to make it compatible with the [JSON-Schema](https://json-schema.org/) format that is expected would be required, could this potentially cause headaches? (alternatively I could be being dense / not knowledgeable enought about the existing schema and this would not be an issue at all!). 

The overall approach of using something to generate the Python classes from the existing schema is definitely something I would support if a sustainable way to do it is found.

**Comment by glenrobson** [comment]
Fortuitously we do have a schema for the IIIF 3 validator and its available here:

 https://github.com/IIIF/presentation-validator/blob/master/schema/iiif_3_0.json

**Comment by glenrobson** [comment]
Just trying out Statham in preparation for the meeting later. 

Problem 1: Statham doesn't like recursion and we have the following instances:
 * Services can be within services for example the [auto complete](https://iiif.io/api/search/1.0/#service-description-1) in the search api
 * Ranges can contain ranges in the [`structures`](https://iiif.io/api/presentation/3.0/#structures) element

**Comment by glenrobson** [comment]
Its possible to customise the name of the generated classes using:

```
"title": "RangeCanvas",
```

Some of the titles in the schema were used for giving instructions on what the error is for the validator but we could use description for this.

**Comment by glenrobson** [comment]
Results of the first test are here:

https://github.com/glenrobson/iiif-prezi/pull/1

Still need to figure out:
 * How to turn classes back into JSON to create Manifest
 * How to add helpers as extensions so we can re-generate.

**Comment by glenrobson** [comment]
Generated the following class:

https://github.com/glenrobson/iiif-prezi/blob/3_with_pydantic/iiif_prezi/prezi3.py

by running:

```
datamodel-codegen --input ../iiif/presentation-validator/schema/iiif_3_0.json --input-file-type jsonschema  --output iiif_prezi/prezi3.py
```

Note creating directly from URL doesn't seem to work...

**Comment by glenrobson** [comment]
This is a round trip of the following manifest https://iiif.io/api/cookbook/recipe/0003-mvm-video/manifest.json:


```
{
    "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/manifest.json",
    "type": "Manifest",
    "label": {
        "en": [
            "Video Example 3"
        ]
    },
    "metadata": null,
    "summary": null,
    "requiredStatement": null,
    "rendering": null,
    "service": null,
    "viewingDirection": null,
    "rights": null,
    "start": null,
    "logo": null,
    "navDate": null,
    "provider": null,
    "seeAlso": null,
    "thumbnail": null,
    "homepage": null,
    "behavior": null,
    "partOf": null,
    "items": [
        {
            "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas",
            "type": "Canvas",
            "label": null,
            "height": 360,
            "width": 640,
            "duration": 572.034,
            "metadata": null,
            "summary": null,
            "requiredStatement": null,
            "rights": null,
            "navDate": null,
            "provider": null,
            "seeAlso": null,
            "thumbnail": null,
            "homepage": null,
            "behavior": null,
            "partOf": null,
            "items": [
                {
                    "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas/page",
                    "type": "AnnotationPage",
                    "label": null,
                    "items": [
                        {
                            "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas/page/annotation",
                            "type": "Annotation",
                            "label": null,
                            "motivation": "painting",
                            "body": {
                                "id": "https://fixtures.iiif.io/video/indiana/lunchroom_manners/high/lunchroom_manners_1024kb.mp4",
                                "type": "Video",
                                "height": 360,
                                "width": 480,
                                "duration": 572.034,
                                "language": null,
                                "service": null,
                                "format": "video/mp4",
                                "label": null
                            },
                            "target": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas"
                        }
                    ]
                }
            ],
            "annotations": null
        }
    ],
    "structures": null,
    "annotations": null
}
```

So we need to exclude the null attributes somehow...

**Comment by glenrobson** [comment]
It had an option to `manifest.json(exclude_unset=True)` and now looks like:

```
{
    "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/manifest.json",
    "type": "Manifest",
    "label": {
        "en": [
            "Video Example 3"
        ]
    },
    "items": [
        {
            "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas",
            "type": "Canvas",
            "height": 360,
            "width": 640,
            "duration": 572.034,
            "items": [
                {
                    "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas/page",
                    "type": "AnnotationPage",
                    "items": [
                        {
                            "id": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas/page/annotation",
                            "type": "Annotation",
                            "motivation": "painting",
                            "body": {
                                "id": "https://fixtures.iiif.io/video/indiana/lunchroom_manners/high/lunchroom_manners_1024kb.mp4",
                                "type": "Video",
                                "height": 360,
                                "width": 480,
                                "duration": 572.034,
                                "format": "video/mp4"
                            },
                            "target": "https://iiif.io/api/cookbook/recipe/0003-mvm-video/canvas"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by glenrobson** [comment]
Output using the following code:

https://github.com/glenrobson/iiif-prezi/blob/e9ef5eceaf5dd3b501890aee0c3ed356d2b967a6/tests/test_prezi3.py#L32

```
{
    "id": "http://iiif.example.org/prezi/Manifest/0",
    "items": [
        {
            "id": "http://iiif.example.org/prezi/Canvas/0",
            "height": 100,
            "width": 200
        },
        {
            "id": "http://iiif.example.org/prezi/Canvas/1",
            "height": 100
        }
    ]
}
```

**Comment by glenrobson** [comment]
With my limited knowledge of python inheritance I've had a go here:

https://github.com/glenrobson/iiif-prezi/blob/3_with_pydantic/iiif_prezi/prezi3helper.py

and test classes:

https://github.com/glenrobson/iiif-prezi/blob/3_with_pydantic/tests/test_prezi3.py

**Comment by mbennett-uoe** [comment]
Something odd I have noticed in the `pydantic` generated classes linked above: The `Manifest` class is overriding the `id` property it inherits from the `Class` class (which in turn is defining the property as an instance of the `Id` class). That means that the validator is not checking it, and it is not being returned in the same format as `id` properties on other classes.

e.g:
```
>>> from prezi3 import Manifest, Canvas
>>> m = Manifest(id="my invalid id")
>>> m.id
'my invalid id'

>>> c = Canvas(id="my invalid id")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Canvas
id -> __root__
  invalid or missing URL scheme (type=value_error.url.scheme)

>>> m = Manifest(id="https://example.org/manifest")
>>> m.id
'https://example.org/manifest'

>>> c = Canvas(id="https://example.org/canvas/1")
>>> c.id
Id(__root__=AnyUrl('https://example.org/canvas/1', scheme='https', host='example.org', tld='org', host_type='domain', path='/canvas/1'))
```

**Comment by mbennett-uoe** [comment]
I have tidied up my examples showing the import of classes via multiple extensions using the `from X import *` technique - including showing how it doesn't work for subclasses loaded from a parent (e.g Canvas objects created by a Manifest loaded from JSON):

https://github.com/mbennett-uoe/iiif-prezi-experiments

**Comment by giacomomarchioro** [comment]
Seems that for forcing the validation  when we set the values after the class instantiation e.g. `manifest.id = 'https..'` we have to change the [model config ](https://pydantic-docs.helpmanual.io/usage/model_config/) setting `validate_assignment = True`.
```python

from pydantic import BaseModel as PydanticBaseModel

class BaseModel(PydanticBaseModel):
    class Config:
         validate_assignment = True
```

This works for the dataclasses that inherit directly from the `BaseModel` class but in my tests seems that it does not affect all the subclasses...

**Comment by mbennett-uoe** [comment]
> EDIT:
> Actually, it works I think the generated data class for the manifest is wrong `id: Optional[Any] = None` the ID is optional and can have any value while it should be mandatory.

I think that this is the issue I spotted above. It would probably be worth spending the time to work out why Pydantic is doing this for the Manifest class, but not elsewhere. If we can't find a way to change this behaviour, then we are getting closer to the territory of abandoning using the auto-generated schema file without modification (at which point we might want to reconsider bringing in the helpers etc)

**Comment by giacomomarchioro** [comment]
> > EDIT:
> > Actually, it works I think the generated data class for the manifest is wrong `id: Optional[Any] = None` the ID is optional and can have any value while it should be mandatory.
> 
> I think that this is the issue I spotted above. It would probably be worth spending the time to work out why Pydantic is doing this for the Manifest class, but not elsewhere. If we can't find a way to change this behaviour, then we are getting closer to the territory of abandoning using the auto-generated schema file without modification (at which point we might want to reconsider bringing in the helpers etc)

Yes, i think at the root of the problem after redefinig the basemodel, is the json schema which maybe can be improved, manifest id and label definitions seem not correct.

**Comment by giacomomarchioro** [comment]
Hi all, 
seems that removing [these two lines from the schema](https://github.com/IIIF/presentation-validator/blob/d4d376e46c966426e6a82e982ea40e149de4819f/schema/iiif_3_0.json#L424-L425) fix this issue. I have opened an issue https://github.com/IIIF/presentation-validator/issues/119 for discussions.

**Comment by giacomomarchioro** [comment]
> Seems that for forcing the validation when we set the values after the class instantiation e.g. `manifest.id = 'https..'` we have to change the [model config ](https://pydantic-docs.helpmanual.io/usage/model_config/) setting `validate_assignment = True`......

I have opened an [issue](https://github.com/mbennett-uoe/iiif-prezi-experiments/issues/1) for discussing the problem of the validation taking advantage of Mike's repository.
